name: Build website

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'api/**'
      - 'web2/**'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'api/**'
      - 'web2/**'
      - 'docs/**'

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: web
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build website
      run: npm run build
    
    - name: Run unit tests
      run: npm run test

    - name: Upload build files
      uses: actions/upload-artifact@v3
      with:
        path: ./web/build