name: Build and deploy API

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  build_api:
    name: Build API
    runs-on: ubuntu-latest
    environment:
      name: api
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install NPM packages
        run: npm ci

      - name: Generate API files
        run: npm run generate:api

      - name: Upload API files
        uses: actions/upload-artifact@v4
        with:
          path: ./api/public
          include-hidden-files: true

  deploy_api:
    name: Deploy API
    runs-on: ubuntu-latest
    environment:
      name: api
    needs: build_api
    if: |
      success() &&
      github.ref == 'refs/heads/main'
    defaults:
      run:
        shell: bash

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: artifact

      - name: Deploy artifacts to the API repo
        uses: tagus/git-deploy@v0.4.1
        with:
          changes: artifact
          repository: git@github.com:clydedsouza/clydedsouza-web-api.git
          ssh_key: ${{ secrets.API_REPO_DEPLOY_KEY }}
          name: clydedsouza
          email: 16275549+clydedsouza@users.noreply.github.com
          clean_repo: true
          branch: main
          message: "Commit from the monorepo API deploy job"
